services:
  conntest:
    container_name: mongodb-conntest
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - CONN_STR=mongodb://user:pass@mongodb
    command: '/bin/bash -c "sleep 5; mongosh $$CONN_STR --eval \"show dbs;\""'
    networks:
      - common
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    networks:
      - common
  mockserver0:
    container_name: mockserver0
    build:
      context: mockserver
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLAKY_WINDOW=${FLAKY_WINDOW:-60}
      - FLAKY_UP_RATIO=${FLAKY_UP_RATIO:-0.25}
      - PID=${PID:-mockserver0}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME:-mongodb}
      - MONGODB_USER=${MONGODB_USER:-user}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD:-pass}
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_DEBUG=${FLASK_DEBUG:-1}
    depends_on:
      - mongodb
    networks:
      - common

  mockserver1:
    container_name: mockserver1
    build:
      context: mockserver
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - FLAKY_WINDOW=${FLAKY_WINDOW:-60}
      - FLAKY_UP_RATIO=${FLAKY_UP_RATIO:-0.8}
      - PID=${PID:-mockserver1}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME:-mongodb}
      - MONGODB_USER=${MONGODB_USER:-user}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD:-pass}
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_DEBUG=${FLASK_DEBUG:-1}
    depends_on:
      - mongodb
    networks:
      - common

  report:
    container_name: report
    build:
      context: report
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME:-mongodb}
      - MONGODB_USER=${MONGODB_USER:-user}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD:-pass}
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_DEBUG=${FLASK_DEBUG:-1}
    depends_on:
      - mongodb
    networks:
      - common

  monitor:
    container_name: monitor
    build:
      context: monitor
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/}
      - MONGODB_DB_NAME=${MONGODB_DB_NAME:-mongodb}
      - MONGODB_USER=${MONGODB_USER:-user}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD:-pass}
    volumes:
      - ./sample.yaml:/app/sample.yaml:ro
    command: ["python", "main.py", "/app/sample.yaml"]
    depends_on:
      - mongodb
    networks:
      - common

networks:
  common:

volumes:
  mongodb: